language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  allow_failures:
    - python: "3.3"
# install dependency:
before_script: pip install twisted
# command to run tests:
script: "py.test"
